openapi: 3.0.3
info:
  title: MASS EDAŞ API
  version: v1
  description: Sayaç veri yönetimi ve sorgulama servisleri
paths: {}
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- BearerAuth: []
