-- MASS_API_KEYS tablosu
CREATE TABLE MASS_API_KEYS (
    API_KEY_ID        NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, -- Otomatik artan ID
    HASHED_API_KEY    VARCHAR2(64) NOT NULL, -- SHA256 hash'i 64 karakter (hex) olur
    DESCRIPTION       VARCHAR2(256),         -- Key'in ne amaçla kullanıldığına dair açıklama (örn: "EPİAŞ Entegrasyon Key 1")
    CREATED_DATE      TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, -- Oluşturulma tarihi
    LAST_USED_DATE    TIMESTAMP(6) WITH LOCAL TIME ZONE, -- En son ne zaman kullanıldığı (opsiyonel, izleme için)
    IS_ACTIVE         NUMBER(1,0) DEFAULT 1 NOT NULL, -- Key'in aktif olup olmadığı (0: pasif, 1: aktif)
    REVOKED_DATE      TIMESTAMP(6) WITH LOCAL TIME ZONE, -- Key'in iptal edildiği tarih
    CONSTRAINT PK_MASS_API_KEYS PRIMARY KEY (API_KEY_ID),
    CONSTRAINT UK_MASS_HASHED_API_KEY UNIQUE (HASHED_API_KEY) -- Hash'lenmiş key'in tekilliğini sağlar
);

-- Index (Arama performansını artırmak için)
CREATE INDEX IDX_MASS_API_KEYS_HASHED_KEY ON MASS_API_KEYS (HASHED_API_KEY);


-- Yorumlar (Dokümantasyon amaçlı)
COMMENT ON TABLE MASS_API_KEYS IS 'MASS Projesi için sistem tarafından üretilen ve API erişimi için kullanılan hashlenmiş API Keylerini saklar.';

COMMENT ON COLUMN MASS_API_KEYS.API_KEY_ID IS 'MASS Projesi için API Key benzersiz tanıtıcısı.';

COMMENT ON COLUMN MASS_API_KEYS.HASHED_API_KEY IS 'MASS Projesi API Keyin SHA256 hash değeri.';
COMMENT ON COLUMN MASS_API_KEYS.DESCRIPTION IS 'MASS Projesi API Keyin kullanım amacını açıklayan metin.';
COMMENT ON COLUMN MASS_API_KEYS.CREATED_DATE IS 'MASS Projesi API Keyin oluşturulduğu tarih ve saat.';
COMMENT ON COLUMN MASS_API_KEYS.LAST_USED_DATE IS 'MASS Projesi API Keyin en son kullanıldığı tarih ve saat.';
COMMENT ON COLUMN MASS_API_KEYS.IS_ACTIVE IS 'MASS Projesi API Keyin aktiflik durumu (1: aktif, 0: pasif).';
COMMENT ON COLUMN MASS_API_KEYS.REVOKED_DATE IS 'MASS Projesi API Keyin iptal edildiği tarih ve saat.';