CREATE TABLE MASS_SUBSCRIPTIONS (
    SUBSCRIPTION_ID      VARCHAR2(36 CHAR) PRIMARY KEY, -- UUID
    SUBSCRIPTION_KEY     VARCHAR2(100 CHAR) NOT NULL,
    INSTALLATION_NUMBER  VARCHAR2(50 CHAR) NOT NULL,
    TYPE                 VARCHAR2(20 CHAR) NOT NULL,
    TCKN                 VARCHAR2(11 CHAR),
    VKN                  VARCHAR2(10 CHAR),
    START_DATE           DATE,
    CREATED_AT           TIMESTAMP DEFAULT SYSTIMESTAMP,
    UPDATED_AT           TIMESTAMP
);

CREATE OR REPLACE TRIGGER TRG_MASS_SUBSCRIPTIONS_ID
BEFORE INSERT ON MASS_SUBSCRIPTIONS
FOR EACH ROW
BEGIN
    IF :NEW.SUBSCRIPTION_ID IS NULL THEN
        :NEW.SUBSCRIPTION_ID := SYS_GUID();
    END IF;
END;

CREATE INDEX IDX_MASS_SUBS_KEY ON MASS_SUBSCRIPTIONS(SUBSCRIPTION_KEY);
CREATE INDEX IDX_MASS_INSTALL_NO ON MASS_SUBSCRIPTIONS(INSTALLATION_NUMBER);
CREATE INDEX IDX_MASS_TYPE ON MASS_SUBSCRIPTIONS(TYPE);
CREATE INDEX IDX_MASS_TCKN ON MASS_SUBSCRIPTIONS(TCKN);
CREATE INDEX IDX_MASS_VKN ON MASS_SUBSCRIPTIONS(VKN);
CREATE INDEX IDX_MASS_START_DATE ON MASS_SUBSCRIPTIONS(START_DATE);


ALTER TABLE MASS_SUBSCRIPTIONS ADD IS_ACTIVE NUMBER(1) DEFAULT 1;
ALTER TABLE MASS_SUBSCRIPTIONS ADD CONSTRAINT CHK_MASS_SUBS_ACTIVE CHECK (IS_ACTIVE IN (0, 1));

ALTER TABLE MASS_SUBSCRIPTIONS ADD LAST_CHECK_DATE TIMESTAMP DEFAULT SYSTIMESTAMP;

ALTER TABLE MASS_SUBSCRIPTIONS MODIFY TYPE VARCHAR2(50);