-- MASS_WEBHOOK_KEYS tablosu
CREATE TABLE MASS_WEBHOOK_KEYS (
    ID      NUMBER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL, -- Otomatik artan ID
    WEBHOOK_URL         VARCHAR2(512) NOT NULL,        -- Webhook URL'i
    PUBLIC_KEY          CLOB NOT NULL,                 -- PEM formatında Public Key
    PRIVATE_KEY         CLOB NOT NULL,                 -- PEM formatında Private Key
    IS_ACTIVE           NUMBER(1,0) DEFAULT 1 NOT NULL,-- Anahtar aktif mi (1: aktif, 0: pasif)
    CREATED_AT       TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL, -- Oluşturulma tarihi
    EXPIRES_AT    TIMESTAMP(6) WITH LOCAL TIME ZONE, -- Anahtar pasife alınma/zaman aşımı tarihi
    CONSTRAINT PK_MASS_WEBHOOK_KEYS PRIMARY KEY (ID)
);

-- Arama performansı için index
CREATE INDEX IDX_MASS_WEBHOOK_KEYS_ACTIVE ON MASS_WEBHOOK_KEYS (IS_ACTIVE);

-- Yorumlar (Dokümantasyon amaçlı)
COMMENT ON TABLE MASS_WEBHOOK_KEYS IS 'MASS Projesi için Webhook bildirimlerinde kullanılacak RSA anahtarlarını ve URL bilgisini saklar.';

COMMENT ON COLUMN MASS_WEBHOOK_KEYS.ID IS 'MASS Projesi Webhook anahtarı için benzersiz tanıtıcı.';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.WEBHOOK_URL IS 'Webhook bildirimlerinin gönderileceği URL.';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.PUBLIC_KEY IS 'PEM formatında public RSA anahtarı.';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.PRIVATE_KEY IS 'PEM formatında private RSA anahtarı.';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.IS_ACTIVE IS 'Anahtarın aktiflik durumu (1: aktif, 0: pasif).';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.CREATED_AT IS 'Anahtarın oluşturulduğu tarih ve saat.';
COMMENT ON COLUMN MASS_WEBHOOK_KEYS.EXPIRES_AT IS 'Anahtarın pasife alındığı (veya süresi dolduğu) tarih ve saat.';
