CREATE TABLE MASS_COMPLAINT_FILES (
    FILE_ID             VARCHAR2(64 CHAR) NOT NULL,
    COMPLAINT_ID        VARCHAR2(32 CHAR),                                 -- Her dosya 1 şikayete bağlı
    NAME                VARCHAR2(255 CHAR) NOT NULL,
    MIME_TYPE           VARCHAR2(100 CHAR) NOT NULL,
    FILE_SIZE                NUMBER NOT NULL,
    UPLOAD_URL          VARCHAR2(1000 CHAR) NOT NULL,
    DOWNLOAD_URL        VARCHAR2(1000 CHAR) NOT NULL,
    UPLOAD_EXPIRES_AT   TIMESTAMP(6) WITH LOCAL TIME ZONE NOT NULL,
    IS_UPLOADED         NUMBER(1) DEFAULT 0 NOT NULL,
    CREATED_AT          TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT          TIMESTAMP(6) WITH LOCAL TIME ZONE,

    CONSTRAINT PK_MASS_COMPLAINT_FILES PRIMARY KEY (FILE_ID),
    CONSTRAINT FK_FILE_TO_COMPLAINT FOREIGN KEY (COMPLAINT_ID)
        REFERENCES MASS_COMPLAINTS(COMPLAINT_ID) ON DELETE CASCADE
);

-- Yorumlar
COMMENT ON TABLE MASS_COMPLAINT_FILES IS 'MASS sisteminde yüklenen şikayet dosyalarını tutar.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.FILE_ID IS 'Dosyanın UUID formatında ID''si.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.COMPLAINT_ID IS 'İlgili şikayet ile ilişki.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.NAME IS 'Dosya adı.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.MIME_TYPE IS 'Dosya tipi (ör: PDF).';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.FILE_SIZE IS 'Boyut (byte).';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.UPLOAD_URL IS 'PUT ile dosya yükleme adresi.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.DOWNLOAD_URL IS 'GET ile dosya indirme adresi.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.UPLOAD_EXPIRES_AT IS 'Upload geçerlilik süresi.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.IS_UPLOADED IS 'Yüklendiyse 1, değilse 0.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.CREATED_AT IS 'Oluşturulma zamanı.';
COMMENT ON COLUMN MASS_COMPLAINT_FILES.UPDATED_AT IS 'Güncellenme zamanı.';
